### ISSUE TITLE
how to get values from the text box?

### ISSUE THREAD

**Issue by 100006** [offner/jquery-editable-select#1]
Let us assume that we are using more than one editable text box. We can give unique id for select tag.
so that we can get values of selection change. If I am editing the text box, how can i get this value from text box?
 Here is my current solution.

```
var value = $("#selectID").val(); // This is the value from dropdown option.
 if (value == null)) { 
     value =  $("#selectID").next().val(); //This is the value from text box.
  };
```

Please correct me if you have better solution. Thanks.

**Comment by offner** [comment]
The class name for the text box is `esTextBox`, so you could write your selector like this:

```
var value = $("#selectID ~ .esTextBox").val();
```

Let me know if that does the trick! It has been a while since I have used this plugin.
